language: node_js
sudo: false
node_js:
  - 'stable'
install:
  - npm install -g codecov
  - npm install sinon
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
  - codecov
on:
  branch: master